### ISSUE TITLE
Create wallet example code in README gives "missing field id" error

### ISSUE THREAD

**Issue by MrHamdulay** [stellar/stellar-wallet-js-sdk#20]

**Comment by bartekn** [comment]
Can you copy a code that is causing this error, response from stellar-wallet server (if any) and commit ID of stellar-wallet and stellar-wallet-js-sdk you are using?

**Comment by MrHamdulay** [comment]
stellar-wallet sha1: 1d53441e4e18e2039bcf81bc8b9d08ba4dd3d2dc
stellar-wallet-js-sdk sha1: e8b1a2f7a446b09c1f190edabc4ff4f58a33f65e

(code with wallet js sdk example)
ubuntu@ubuntu-VirtualBox:~/test$ node test.js
Unknown error.

(wallet server)
ubuntu@ubuntu-VirtualBox:~/stellar-wallet$ stex www --watch
stellar-wallet-28151 listening on port 3000
HTTP request
HTTP response


After putting a bunch of console.log's everywhere the problem seemed to be that an "id" field was missing from the request that came from the sdk

**Comment by bartekn** [comment]
Make sure you're adding `/v2` suffix to `server` param. Like this:
```js
StellarWallet.createWallet({
  server: "http://localhost:3000/v2"
// ...
```
I will update readme file.

**Comment by MrHamdulay** [comment]
Thanks!
